// setup-clips.js
// Run this from your neuro-recover-videos folder
// It confirms the clip files are in the right place
const fs = require('fs');
const path = require('path');

const clips = [
  'clip-dashboard.mp4',
  'clip-progress.mp4', 
  'clip-piano.mp4',
  'clip-fingertap.mp4',
  'clip-bubbles.mp4',
];

const missing = clips.filter(c => !fs.existsSync(path.join('public', c)));
if (missing.length === 0) {
  console.log('✅ All video clips are in place. Ready to preview!');
  console.log('Run: npx remotion studio --force-new');
} else {
  console.log('❌ Missing clips in public/:', missing);
  console.log('These clips were generated by Claude and should have been downloaded.');
  console.log('Ask Claude to re-generate them if needed.');
}
